### ISSUE TITLE
Progress dialog

### ISSUE THREAD

**Issue by sethgnavo** [javiersantos/AppUpdater#14]
Showing a progress dialog (indeterminate) when checking for update would be nice.

**Comment by sethgnavo** [comment]
I'm working for a pull request

**Comment by javiersantos** [comment]
The library aim to show a message only when a new update is available, without showing a indeterminate dialog everytime (that could be annoying). Anyway, if you want to show an indeterminate dialog (for example, when an user click a button) you can programatically show one and dismiss it when the asynchronous [AppUpdaterUtils method](https://github.com/javiersantos/AppUpdater#other-features) is completed.

I think there is no need to include an indeterminate dialog in the library, since the library doesn't aim to make the user wait.
