### ISSUE TITLE
Staged rollout on Google Play

### ISSUE THREAD

**Issue by paab72** [javiersantos/AppUpdater#54]
Is there any issue with staged rollout and AppUpdater? What if the user is not part of the staged group, but the AppUpdater is. Do you see any issue?

**Comment by javiersantos** [comment]
Staged rollouts are not supported by the library since the latest version is retrieved using the app details in the web version of the Play Store and doesn't matter the user who is using the app. I think that the Play Store will show the update when the staged rollout has been completed (but I am not sure).
