### ISSUE TITLE
Force Update

### ISSUE THREAD

**Issue by karopass** [javiersantos/AppUpdater#73]
Hi ! This is one of the best Library in this category. I really impressed and want implement in my some applications. I want know some information before go ahead.

**1. How can we force user to update application ?
2. if URL that have XML uploaded is down, Application will work normal or will crashed /
3. Can we debug application and check library function if Application is not published yet ?**

Thanks

**Comment by javiersantos** [comment]
> How can we force user to update application?

It's not supported by the library. You should use `AppUpdaterUtils` and implement your own non-cancelable dialog: https://github.com/javiersantos/AppUpdater/blob/master/README.md#appupdaterutils

> If URL that have XML uploaded is down, Application will work normal or will crashed

The app won't crash and you will see a log message.

> Can we debug application and check library function if Application is not published yet?

It depends on the source you are using for the updates. I recommend you to use `UpdateFrom.JSON` in order to debug your app and the library.
